In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
direct_link = 'https://assets.datacamp.com/production/repositories/655/datasets/2a1f3ab7bcc76eef1b8e1eb29afbd54c4ebf86f2/eurovision-2016.csv'

In [3]:
df = pd.read_csv(direct_link)

In [8]:
df

,From country,To country,Jury A,Jury B,Jury C,Jury D,Jury E,Jury Rank,Televote Rank,Jury Points,Televote Points
0,Albania,Belgium,20,16,24,22,24,25,14,NaN,NaN
1,Albania,Czech Republic,21,15,25,23,16,22,22,NaN,NaN
2,Albania,The Netherlands,22,14,23,24,21,24,24,NaN,NaN
3,Albania,Azerbaijan,19,12,11,21,11,13,19,NaN,NaN
4,Albania,Hungary,8,13,9,14,9,10,10,1.0,1.0
5,Albania,Italy,4,10,3,7,2,3,2,8.0,10.0
6,Albania,Israel,10,2,18,4,12,8,17,3.0,NaN
7,Albania,Bulgaria,11,3,6,13,6,7,3,4.0,8.0
8,Albania,Sweden,16,8,15,6,15,11,8,NaN,3.0
9,Albania,Germany,18,17,20,11,17,18,15,NaN,NaN
10,Albania,France,3,9,1,9,1,2,11,10.0,NaN
11,Albania,Poland,14,7,13,20,22,14,6,NaN,5.0
12,Albania,Australia,1,1,2,1,3,1,1,12.0,12.0
13,Albania,Cyprus,25,11,21,25,20,23,12,NaN,NaN
14,Albania,Serbia,15,26,12,15,19,19,26,NaN,NaN
15,Albania,Lithuania,13,18,22,17,23,20,7,NaN,4.0
16,Albania,Croatia,24,19,16,18,18,21,20,NaN,NaN
17,Albania,Russia,7,4,7,5,7,4,4,7.0,7.0
18,Albania,Spain,9,5,4,12,4,5,23,6.0,NaN
19,Albania,Latvia,23,20,17,8,13,17,21,NaN,NaN
20,Albania,Ukraine,17,25,8,2,8,12,5,NaN,6.0
21,Albania,Malta,5,21,5,16,5,9,16,2.0,NaN
22,Albania,Georgia,26,22,26,26,26,26,25,NaN,NaN
23,Albania,Austria,6,23,19,19,14,16,13,NaN,NaN
24,Albania,United Kingdom,2,6,10,10,10,6,18,5.0,NaN
25,Albania,Armenia,12,24,14,3,25,15,9,NaN,2.0
26,Armenia,Belgium,12,6,9,6,6,7,17,4.0,NaN
27,Armenia,Czech Republic,13,14,12,8,9,10,18,1.0,NaN
28,Armenia,The Netherlands,11,12,14,16,10,11,11,NaN,NaN
29,Armenia,Azerbaijan,25,25,25,19,25,25,25,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1036,Ukraine,Malta,18,17,20,22,19,20,19,NaN,NaN
1037,Ukraine,Georgia,8,8,11,5,15,8,5,3.0,6.0
1038,Ukraine,Austria,19,19,15,19,16,19,12,NaN,NaN
1039,Ukraine,United Kingdom,24,18,19,10,13,18,23,NaN,NaN
1040,Ukraine,Armenia,13,20,7,21,17,15,4,NaN,7.0
1041,United Kingdom,Belgium,14,3,20,10,7,11,14,NaN,NaN
1042,United Kingdom,Czech Republic,12,17,17,15,24,19,22,NaN,NaN
1043,United Kingdom,The Netherlands,8,19,15,8,17,14,12,NaN,NaN
1044,United Kingdom,Azerbaijan,25,23,25,21,22,25,23,NaN,NaN
1045,United Kingdom,Hungary,4,14,23,20,15,16,16,NaN,NaN
1046,United Kingdom,Italy,13,20,18,22,25,22,20,NaN,NaN
1047,United Kingdom,Israel,5,5,14,9,19,8,17,3.0,NaN
1048,United Kingdom,Bulgaria,10,4,21,3,9,6,3,5.0,8.0
1049,United Kingdom,Sweden,24,25,9,25,23,24,10,NaN,1.0
1050,United Kingdom,Germany,19,24,19,23,14,23,21,NaN,NaN
1051,United Kingdom,France,6,10,5,7,11,5,11,6.0,NaN
1052,United Kingdom,Poland,16,21,24,14,8,18,2,NaN,10.0
1053,United Kingdom,Australia,3,6,6,4,12,3,5,8.0,6.0
1054,United Kingdom,Cyprus,1,7,2,11,16,4,9,7.0,2.0
1055,United Kingdom,Serbia,9,11,16,6,10,9,24,2.0,NaN
1056,United Kingdom,Lithuania,7,8,13,19,3,7,1,4.0,12.0
1057,United Kingdom,Croatia,21,12,10,5,6,10,25,1.0,NaN
1058,United Kingdom,Russia,20,16,11,13,2,13,4,NaN,7.0
1059,United Kingdom,Spain,17,18,22,16,21,21,7,NaN,4.0
1060,United Kingdom,Latvia,22,9,4,12,20,15,8,NaN,3.0
1061,United Kingdom,Ukraine,11,1,1,1,5,2,6,10.0,5.0
1062,United Kingdom,Malta,18,13,8,17,4,12,15,NaN,NaN
1063,United Kingdom,Georgia,2,2,3,2,1,1,19,12.0,NaN
1064,United Kingdom,Austria,23,15,12,18,13,17,13,NaN,NaN
1065,United Kingdom,Armenia,15,22,7,24,18,20,18,NaN,NaN

In [14]:
country_names = df.iloc[:,0]

In [17]:
sample = df.iloc[:,2:]

In [18]:
from scipy.cluster.hierarchy import linkage, dendrogram

# Calculate the linkage: mergings
mergings = linkage(sample, method = 'single')

dendrogram(
    mergings, 
    labels = country_names,
    leaf_rotation=90,
    leaf_font_size=6)

ValueError: The condensed distance matrix must contain only finite values.